---
title: "Self-Assessment vs. Clinical-Assessment Models for Thyroid Cancer"
author: "Dan Huang, Yuchen Li, Zhenzhong Zhang, & Evan Rhodes"
format:
  html:
    toc: true
    toc-depth: 2
    number-sections: true
    embed-resources: true
    code-fold: true
    code-tools: false
execute:
  echo: false
  warning: false
  message: false
editor: visual
---

```{r}
#| label: setup
# Load required packages
suppressPackageStartupMessages({
  library(tidyverse)
  library(broom)
  library(broom.mixed)
  library(geepack)
  library(lme4)
  library(scales)
  library(MASS)      # for glm.nb
})
```

ER NOTE: Using this document to draft writing portions of the project. Intention is that we can work together on writing portions & paste into final knitted report (my assumption is that we’ll be working on R code individually, & so this document will keep us from writing separate reports in quarto/rmarkdown that we’d need to merge later)

Introduction

Thyroid cancer has seen increasing prevalence and mortality in recent decades, largely in part to improved diagnostic technologies and early detection methods in the medical field; in addition, growing tumor sizes and observed disparities between demographics groups raise concern that there are true environmental or lifestyle factors at play as well.1 The diagnosis pipeline generally begins with a physical exam to identify any lumps or swelling around the neck area with ultrasound, fine-needle aspiration, or electrography scans to follow for investigation into the nodule’s benign or malignant status. A benign nodule often does not require any major intervention unless it is large enough to cause alternative issues, while malignant nodules can spread cancerous cells throughout the body and must be quickly treated. Research to date has identified an array of different risk factors that can help determine the probability of malignancy in a particular thyroid nodule, ranging across basic demographics information, diagnostic scan results, and basic health aspects that the average person may have access to through wearable technology (i.e. heart rate, sleep patterns, etc.). There are a multitude of studies investigating the impact of these risk factors on thyroid cancer pathologies for malignancy status and cancer subtypes, with a common finding that diagnostic scans are beneficial but do not reliability differentiate benign from malignant nodules.2 To that end, careful consideration of additional demographics and other health measurements from blood tests, wearable data, and other sources must be considered when investigating a patient with potential thyroid cancer. 

With different levels of access to the various tiers of thyroid cancer diagnostics, natural questions regarding how models targeting these levels of access would perform when compared to each other in predicting thyroid nodule malignancy status. For example, risk factors such as age, gender, weight, and family history are easily accessible to the average person without the need for professional equipment. Similarly, rising popularity in wearable technology that can measure biological functions can provide a large portion of the population with easily referenced heart rates, daily steps, or even estimated stress levels. Obtaining risk factors from these sources requires much less patient burden when compared to visiting a clinical setting for diagnostics and testing. To explore the potential gain of a thyroid cancer malignancy status prediction model designed for at-home patient use, the research team has proposed comparing a self-assessment model utilizing only features that a patient could obtain themself to a clinical-assessment model utilizing only features from professional technologies. These analyses are purely exploratory in nature, targeting facets of patient burden and access in pursuing thyroid cancer treatment as opposed to treatment or disease mechanisms themselves. In addition, thyroid cancer subtypes will not be accounted for as they have differing pathological routes and the intention is to attempt to predict any cancer present as opposed to specific cancer type. The team hopes to identify the most prevalent risk factors for malignant thyroid nodules in both the self-assessment and clinical-assessment pools for comparison with current literature. In practice, it would be expected that formal statistical models include features from both assessment pools. For the purposes of this exploration however, the research team presumes that the clinical-assessment model will perform better than the self-assessment model since clinical-assessment measurements directly concern the nodule whose malignancy status is in question. 

To perform analyses, the study team elected to use a multi-visit thyroid cancer monitoring data available for public download on Kaggle. The data contain two to five visits across 80,000 unique participants over January 2015 to March 2025. Patient information has been de-identified for public use and no missing values are present in the data; collection sources included participating healthcare centers and wearable device logs that were supplied by the participants. There is a rich selection of risk factors to take from, including demographic information, scan results, blood test results, and wearable device measurements. Available features were categorized into self- or clinical-assessment bins and review of the current literature informed predictor selection after categorization.  


Methods

Demographic/Wearable (i.e. ‘Self Assessment’) Characteristics Model 

The aim for this model is to investigate how demographic and self-assessment characteristics are associated with the probability of "Malignant". The outcome is the cancer diagnosis result (Diagnosis_Label) with the coding of 0 being “Benign” or non-cancerous and 1 being “Malignant” or cancerous.

The predictors used for this model include the demographics variables: age, gender, BMI, family history, smoking status, radiation exposure; the time varying self-assessment measures: heart rate, daily steps, sleep patterns, body temperature, pulse oximetry, stress level, symptom onset duration, medication adherence and the time effect (visit number).

Generalized Linear Models (GLM), Generalized Estimating Equations (GEE), and Generalized Linear Mixed Models (GLMM) were each applied to evaluate the associations between self-assessment characteristics and cancer diagnosis. The results from the three modeling approaches were then compared and discussed.

Data preprocessing for the GLM, GEE, and GLMM are consistent: All the continuous covariates were centered and scaled, which include: age, BMI, and all the time varying self-assessment measures. Then, the visit number was defined as numbers and patient ID was used as a grouping factor.

First, a logistic GLM was fitted and the exponentiated odds ratio and 95% confidence intervals were calculated. While GLM assumes independence, homoscedasticity, linearity and an exponential family distribution, our dataset contains repeated measures, meaning observations within the same subject are correlated. Since the data are in long format, the independence assumption was clearly violated but was nonetheless assumed for the purpose of fitting the GLM. The GLM was solely used as a comparison model against the GEE and GLMM and is not intended to provide valid reference for correlated data. The deviance residuals vs. fitted plot was plotted to check the GLM assumptions.

Next, a GEE model was applied using an exchangeable working correlation structure, and odds ratios with robust standard errors were obtained. The working correlation (α) was estimated from the data. To assess sensitivity to the choice of correlation structure, we additionally fit GEE models assuming independence and AR-1 and compared their results with those from the exchangeable model. Key GEE assumptions include correctly specifying the link function and working covariance structure, accommodating correlated responses, and relying on robust variance estimates for valid inference. Pearson residuals versus fitted values were examined to assess model fit.

GLMM:
[Steps]
[Assumptions]
[diagnostics]


Tumor/Requires Scan or other test (i.e. ‘Clinical Assessment’) Characteristics Model


For the clinical-assessment model, current literature regarding thyroid cancer diagnostic scan risk factors and association of other blood test measurements present in the analysis dataset was reviewed. Across sources, tumor size and shape was commonly reported as a major indicator of malignancy and subsequent malignant growths.2, 3 In addition, Woliński et al. suggest that decreased elasticity, microcalcifications, and irregular margins from diagnostic scans of the nodule also increase malignancy risk.2 As such, relevant variables present in the curated Kaggle dataset resulting from diagnostic scans were included in the clinical-assessment model. Another scan diagnostic feature recommended for thyroid cancer malignancy status is echogenicity, a measure of how well a certain tissue can reflect sound waves from ultrasound imaging.5 The final scan diagnostic measurement that was included in the clinical-assessment model was the image entropy, a statistical representation of the scan image’s disorder; it has been posed that capturing intratumor heterogeneity was associated with gene-expression patterns, which can be used to help improve decisions in pursuing cancer treatments.6 

Aside from quantifications in diagnostic scans, common blood tests at the clinic can also provide several key risk factors for thyroid nodule malignancy. From blood tests, medical providers can obtain a measure of thyroid-stimulating hormone (TSH), which recent studies have presented could help provide additional information to predict malignancy 7 since it is possible that increasing TSH concentrations could promote neoplasia and carcinogenesis on thyroid tissue.4 In addition, other variables available in the public dataset that fall into this blood test sub-category include measures of thyroid peroxidase antibodies (TPOAb) and thyroglobulin antibodies (TGAB) that are also determined to potentially assist in diagnosing malignant thyroid tumors.7 

All non-categorical features selected for model use were scaled and centered before proceeding with analyses. As this work is exploratory in nature, one goal is to compare risk factor influence on the overall model and we can achieve a crude comparison by ensuring that all of our coefficient interpretations represent the same scale of change; in addition, scaling and centering helps with interpretation of many of the feature estimates whose values are bounded from zero to one. Dummy coding for reference cell interpretation was implemented for any binary indicator or categorical variable. 

As an initial step into this exploratory analysis, a generalized estimating equation (GEE) model was fit using nodule benign or malignancy status as the binary response and all diagnostic measurements previously mentioned as pre-determined fixed effects. Due to the robust nature of GEE estimates and guards against mis-specified within-participant correlation structures, it was determined that this would be an adequate initial model to investigate with an assumed exchangeable correlation structure. Once the initial model is applied, empirical correlations calculated by Pearson residuals will be plotted to determine the observed correlation structure over time lags, with a max time lag of four visits. These correlations by visit lag time will be used to assess the exchangeable correlation structure selection and switch to an AR(1) structure if necessary. Final results and coefficient influence will be interpreted from whichever correlation structure appears most appropriate according to the empirical correlations. The study team notes that malignancy/benign nodule status does not change over patient visits, indicating little within-subject variation that may likely cause GEE to struggle with this problem context, which requires a moderate amount of variation for estimation algorithms to be appropriate. A Pearson residual plot against fitted model probability values will be reviewed to identify any majorly outlying data points and confirm appropriate mean and variance structures have been applied. 

Next, a generalized linear model (GLM) approach was used while subsetting the data to only the baseline visit, making an assumption that participant’s measurements at their first visit should be indicative of their tumor status, given that tumor status did not change over time. A similar workflow will be applied, reviewing model estimates for the predetermined clinical risk factors and interpreting predictor influence. Deviance and Pearson residual plots will be reviewed for adequate model fit. Though there is a major assumption in baseline visit measurements being solely indicative of tumor status, this limitation helps satisfy GLM requirements of independent observations. Some bias will likely be introduced by this approach, but model estimates for risk factors will be more indicative of true population-level effects that may be invalid under a GEE approach.  

GLMM:
[Steps]
[Assumptions]
[diagnostics]

Describe how self vs. clinical assessment models will be compared




Results

Demographic/Wearable (i.e. ‘Self Assessment’) Characteristics Model 

Table 1: Logistic GLM Exponentiated ORs + 95% CIs

P-values of BMI and Family History are less than 0.05, meaning that they are statistically significant for cancer diagnosis. However, the effects are small (ORs: 1.022, 1.037). Because the outcome was in fact constant across visits for each patient, what the GLM captures is how average demographics and self-assessment features differ between malignant vs benign patients. Since independence was assumed, repeated measures oversample patients with more visits, meaning that the standard errors are likely to be underestimated. 

Figure 1: Deviance residuals vs fitted
The deviance residuals vs fitted plot shows two lines with no curvature or clear patterns, which are expected for binary outcome, suggesting no lack of fit. Linearity was assured, but independence assumption was violated inherently.

Table 2: Exchangeable GEE: Exponentiated ORs & robust SEs
Table 3: Working Correlation (Alpha)

The working correlation was approximately 1. Since outcome stays the same for each patient, within-subject outcomes have no variation and correlation can't be estimated. There was no significant predictor. Estimates are similar to GLM, but robust standard errors are larger.

Table 4: Independence GEE: Exponentiated ORs & robust SEs
Table 5: AR-1 GEE: Exponentiated ORs & robust SEs

ORs and 95% CIs are almost identical for the independence, exchangeable, and AR-1 working correlations. This is expected because outcome is consistent within each subject, and the assumed correlation structure has no impact on the estimates. For the independence model, BMI was significant due to smaller standard errors.

Figure 2: Pearson residuals vs fitted
There was no strong pattern, which suggests that the mean model is reasonably specified. Since N is large (80,000), the robust standard errors are reliable. Residuals only reflect constant diagnosis outcome.

GLMM
Table 6:

[Interpretation]

Figure 3:
[Interpretation]



Tumor/Requires Scan or other test (i.e. ‘Clinical Assessment’) Characteristics Model

Table 7: Clinical-Assessment Logistic GLM Exponentiated ORs + 95% CIs
Figure 4. Clinical-Assessment Logistic GLM Plot of Centered & Scaled Coefficients

Discuss significant predictors, feature importance. Discuss how limiting to baseline gives us a cross-sectional population level view of initial tumor diagnoses

Figure 5. Clinical-Assessment Logistic GLM Pearson & Deviance Residuals 

Panel these two plots into one figure side by side; discuss fine mean/variance structure, but model seems to struggle with those who have malignant statuses

Table 8: Clinical-Assessment GEE Exponentiated ORs + 95% CIs
Figure 6. Clinical-Assessment GEE Plot of Centered & Scaled Coefficients

Discuss how GEE fails here due to no within-subject variability. Discuss how estimates we see are mostly random noise, incredibly small and all odds ratios = 1. I don’t think there’s any point in plotting the residuals for this one

GLMM
Table 9:

[Interpretation]

Figure 7:
[Interpretation]




ER NOTES:
Discuss no variability in outcome causes GEE to fail (working correlations =1, all estimates close to 0 -> all odds ratios =1); since very little within-person variability, GEE not appropriate
GLM model seems to fit, but underestimating probability of malignancy in those who have it  (about 17-18% prevalence of malignancy among the 80,000 participants)





Discussions & Conclusions

Demographic/Wearable (i.e. ‘Self Assessment’) Characteristics Model 

GLM vs GEE vs GLMM
[compare/contrast the results]
[compare/contrast the diagnostics]

DH notes:
GLM and GEE have similar estimates/ORs, but GLM has smaller SEs from repeated measures. GLM identified BMI and family history as significant predictors, but since within-patient correlation was accounted for in GEE and GLMM, they were no longer significant. GLM’s results were significant because independence was assumed for the purpose of fitting the model. 
All three target between-patient association since there’s no variation across visits, rather than longitudinal effects.


Tumor/Requires Scan or other test (i.e. ‘Clinical Assessment’) Characteristics Model

GLM vs GEE vs GLMM
[compare/contrast the results]
[compare/contrast the diagnostics]

Self vs. Clinical Assessment Model Comparisons 





Limitations, Future Work, Final Thoughts

This study has several worth noticing limitations. First, the outcome (thyroid cancer diagnostics) is consistent across visits within each subject. Although the data have a longitudinal structure, the analysis is effectively cross-sectional when modeling cancer diagnostic outcomes. As a result, the estimates from GLM, GEE and GLMM reflect between-patient differences rather than within-patient changes over time.
 
Second, for the purpose of comparing different models, GLM treated within subject data as independent, which reduced smaller standard errors because identical outcomes were counted multiple times.

Third, diagnostic scans may vary across clinics and devices, which lead to unequal variance from measurement errors. 

Finally, misclassification of the label, noise in self assessment measures and limited dataset documentation may contribute additional bias to the results.

To improve the analysis, the most important step is to address the outcome issue. Since diagnosis status does not change across visits, the current models only estimate between-patient differences. Future work should select an outcome that can vary longitudinally, such as nodule size, stress level, or vascularity score, in order for the GEE and GLMM to produce meaningful longitudinal results. 

Beyond outcome selection, other improvements include adding thyroid cancer subtypes to the model, combining self-assessment and clinical models, improving model complexity by adding interactions, and accounting for center differences by split analysis by center. These changes could strengthen the analysis and improve statistical powder.

ER NOTES
 for clinical limitations, could add a statement about how we assume that scans are consistently accurate across different scan types (ultrasound, FNA, elastography); point of research question is to compare clinical vs. self assessments, don’t want to induce extra variability in potential scan type inconsistencies
Another limitation could be lack of documentation for dataset / trust data is real / unsure if any imputation methods were used 
Might be worth mentioning intention behind project was mostly explorative, not strictly rooted in cancer science (i.e. don’t understand scan features etc. 100%)

References 

Pellegriti, Gabriella, et al. “Worldwide Increasing Incidence of Thyroid Cancer: Update on Epidemiology and Risk Factors.” Journal of Cancer Epidemiology, vol. 2013, 2013, pp. 1–10. DOI.org (Crossref), https://doi.org/10.1155/2013/965212. 
Usefulness of Different Ultrasound Features of Malignancy in Predicting the Type of Thyroid Lesions: A Meta‑analysis of Prospective Studies. https://doi.org/10.20452/pamw.2132. Accessed 26 Nov. 2025.
Gu, Jianhua, et al. “A Machine Learning-Based Approach to Predicting the Malignant and Metastasis of Thyroid Cancer.” Frontiers in Oncology, vol. 12, Dec. 2022, p. 938292. DOI.org (Crossref), https://doi.org/10.3389/fonc.2022.938292.
Ross, Douglas S. “Predicting Thyroid Malignancy.” The Journal of Clinical Endocrinology & Metabolism, vol. 91, no. 11, Nov. 2006, pp. 4253–55. DOI.org (Crossref), https://doi.org/10.1210/jc.2006-1772.
Wu, MH., Chen, CN., Chen, KY. et al. Quantitative analysis of echogenicity for patients with thyroid nodules. Sci Rep 6, 35632 (2016). https://doi.org/10.1038/srep35632
Incoronato, Mariarosaria, et al. “Radiogenomic Analysis of Oncological Data: A Technical Survey.” International Journal of Molecular Sciences, vol. 18, no. 4, Apr. 2017, p. 805. DOI.org (Crossref), https://doi.org/10.3390/ijms18040805.
Li, Luchuan, et al. “Positive Thyroid Peroxidase Antibody and Thyroglobulin Antibody Are Associated With Better Clinicopathologic Features of Papillary Thyroid Cancer.” Endocrine Practice, vol. 27, no. 4, Apr. 2021, pp. 306–11. DOI.org (Crossref), https://doi.org/10.1016/j.eprac.2020.10.017. 
